### ISSUE TITLE
Add cc protocol

### ISSUE THREAD

**Issue by stephencode** [stephencode/blog#3]
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)

署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)

I hate the people who copy other's knowledge without consent. 🔥  So I will add this protocol to each post. 🙈

**Comment by stephencode** [comment]
Refer to @lengzzz blog~ [lengzzz](https://lengzzz.com/note/about-me) 👍

**Comment by zwh8800** [comment]
😄 你也是自己开发的博客呀

**Comment by stephencode** [comment]
感觉打扰到你了，不过因为是看了你的简洁大气的博客，然后注意到文末的cc协议，所以有必要告知一声~~
嗯，自己有能力，为何不做一个呢？ 🙊 🙊 🙊

**Comment by stephencode** [comment]
Like this 🙉 :
![image](https://user-images.githubusercontent.com/17685647/29847797-0d3a00b0-8d50-11e7-959a-d6267f52a440.png)

**Comment by zwh8800** [comment]
nice

**Comment by stephencode** [comment]
@zwh8800 Thx 😃
